'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property check1() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("check1"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("check1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property check2() As Boolean
            Get
                Return CType(Me("check2"),Boolean)
            End Get
            Set
                Me("check2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property check3() As Boolean
            Get
                Return CType(Me("check3"),Boolean)
            End Get
            Set
                Me("check3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property check4() As Boolean
            Get
                Return CType(Me("check4"),Boolean)
            End Get
            Set
                Me("check4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property check5() As Boolean
            Get
                Return CType(Me("check5"),Boolean)
            End Get
            Set
                Me("check5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Stretch")>  _
        Public Property bg_image() As Global.System.Windows.Forms.ImageLayout
            Get
                Return CType(Me("bg_image"),Global.System.Windows.Forms.ImageLayout)
            End Get
            Set
                Me("bg_image") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BackgroundImageName() As String
            Get
                Return CType(Me("BackgroundImageName"),String)
            End Get
            Set
                Me("BackgroundImageName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Stretch")>  _
        Public Property bgimage() As Global.System.Windows.Forms.ImageLayout
            Get
                Return CType(Me("bgimage"),Global.System.Windows.Forms.ImageLayout)
            End Get
            Set
                Me("bgimage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property varible() As String
            Get
                Return CType(Me("varible"),String)
            End Get
            Set
                Me("varible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstTimeUsed() As Boolean
            Get
                Return CType(Me("FirstTimeUsed"),Boolean)
            End Get
            Set
                Me("FirstTimeUsed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Game() As String
            Get
                Return CType(Me("Game"),String)
            End Get
            Set
                Me("Game") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Gamepath() As String
            Get
                Return CType(Me("Gamepath"),String)
            End Get
            Set
                Me("Gamepath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SSEEdit() As String
            Get
                Return CType(Me("SSEEdit"),String)
            End Get
            Set
                Me("SSEEdit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FNIS() As String
            Get
                Return CType(Me("FNIS"),String)
            End Get
            Set
                Me("FNIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("612")>  _
        Public Property form1_sizeX() As String
            Get
                Return CType(Me("form1_sizeX"),String)
            End Get
            Set
                Me("form1_sizeX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("266")>  _
        Public Property form1_sizeY() As String
            Get
                Return CType(Me("form1_sizeY"),String)
            End Get
            Set
                Me("form1_sizeY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PLAY0_Btn() As String
            Get
                Return CType(Me("PLAY0_Btn"),String)
            End Get
            Set
                Me("PLAY0_Btn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Play_btn() As String
            Get
                Return CType(Me("Play_btn"),String)
            End Get
            Set
                Me("Play_btn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Play_Btn_Mouseover() As String
            Get
                Return CType(Me("Play_Btn_Mouseover"),String)
            End Get
            Set
                Me("Play_Btn_Mouseover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Options_Btn() As String
            Get
                Return CType(Me("Options_Btn"),String)
            End Get
            Set
                Me("Options_Btn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Options_Btn_mouseover() As String
            Get
                Return CType(Me("Options_Btn_mouseover"),String)
            End Get
            Set
                Me("Options_Btn_mouseover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Exit_Btn() As String
            Get
                Return CType(Me("Exit_Btn"),String)
            End Get
            Set
                Me("Exit_Btn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Exit_Btn_mouseover() As String
            Get
                Return CType(Me("Exit_Btn_mouseover"),String)
            End Get
            Set
                Me("Exit_Btn_mouseover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("349, 146")>  _
        Public Property Play_btn_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("Play_btn_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Play_btn_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("164, 43")>  _
        Public Property PLAY0_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("PLAY0_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("PLAY0_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("164, 43")>  _
        Public Property OPTIONS0_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("OPTIONS0_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("OPTIONS0_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("164, 43")>  _
        Public Property EXIT0_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("EXIT0_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("EXIT0_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("436, 21")>  _
        Public Property Play_Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Play_Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Play_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("436, 95")>  _
        Public Property OPTIONS_location() As Global.System.Drawing.Point
            Get
                Return CType(Me("OPTIONS_location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("OPTIONS_location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("436, 164")>  _
        Public Property Exit_location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Exit_location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Exit_location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Opacity_Play() As String
            Get
                Return CType(Me("Opacity_Play"),String)
            End Get
            Set
                Me("Opacity_Play") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Opacity_Options() As String
            Get
                Return CType(Me("Opacity_Options"),String)
            End Get
            Set
                Me("Opacity_Options") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Opacity_Exit() As String
            Get
                Return CType(Me("Opacity_Exit"),String)
            End Get
            Set
                Me("Opacity_Exit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Custom1_visible() As Boolean
            Get
                Return CType(Me("Custom1_visible"),Boolean)
            End Get
            Set
                Me("Custom1_visible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomButton1_Image() As String
            Get
                Return CType(Me("CustomButton1_Image"),String)
            End Get
            Set
                Me("CustomButton1_Image") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Application_Buttton1() As String
            Get
                Return CType(Me("Application_Buttton1"),String)
            End Get
            Set
                Me("Application_Buttton1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property Button1() As Global.System.Drawing.Point
            Get
                Return CType(Me("Button1"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Button1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PlayPosition1() As String
            Get
                Return CType(Me("PlayPosition1"),String)
            End Get
            Set
                Me("PlayPosition1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PlayPosition2() As String
            Get
                Return CType(Me("PlayPosition2"),String)
            End Get
            Set
                Me("PlayPosition2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SettingsPosition1() As String
            Get
                Return CType(Me("SettingsPosition1"),String)
            End Get
            Set
                Me("SettingsPosition1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SettingsPosition2() As String
            Get
                Return CType(Me("SettingsPosition2"),String)
            End Get
            Set
                Me("SettingsPosition2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExitPosition1() As String
            Get
                Return CType(Me("ExitPosition1"),String)
            End Get
            Set
                Me("ExitPosition1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExitPosition2() As String
            Get
                Return CType(Me("ExitPosition2"),String)
            End Get
            Set
                Me("ExitPosition2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TESVMP_Launcher.My.MySettings
            Get
                Return Global.TESVMP_Launcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
